In [3]:
import yfinance as yf
print(yf.__version__)

0.2.40

In [1]:
import yfinance as yf
print(yf.__version__)

1.2.0

/Users/gularahuseynli/Documents/bank-treasury-sensitivity/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
import pandas_datareader.data as web
import datetime

START = "2015-01-01"
END = "2026-09-04"

tickers = ["JPM", "BAC", "GS", "^GSPC"]
stock_prices = yf.download(tickers, start=START, end=END)["Close"]
stock_prices.to_csv("../data/raw/stock_prices.csv")
stock_prices.head()

[*********************100%***********************]  4 of 4 completed

Ticker            BAC          GS        JPM        ^GSPC
Date
2015-01-02  13.979469  154.117813  46.066788  2058.199951
2015-01-05  13.573362  149.305878  44.636642  2020.579956
2015-01-06  13.167254  146.285431  43.479256  2002.609985
2015-01-07  13.229733  148.465546  43.545605  2025.900024
2015-01-08  13.503080  150.835876  44.518688  2062.139893

In [3]:
start = datetime.datetime.strptime(START, "%Y-%m-%d")
end = datetime.datetime.strptime(END, "%Y-%m-%d")
treasury = web.DataReader(["DGS10", "DGS2"], "fred", start, end)
treasury.to_csv("../data/raw/treasury_yields.csv")
treasury.head()

            DGS10  DGS2
DATE
2015-01-01    NaN   NaN
2015-01-02   2.12  0.66
2015-01-05   2.04  0.68
2015-01-06   1.97  0.65
2015-01-07   1.96  0.62

In [4]:
vix = yf.download("^VIX", start=START, end=END)["Close"]
vix.to_csv("../data/raw/vix.csv")
vix.head()

[*********************100%***********************]  1 of 1 completed

Ticker           ^VIX
Date
2015-01-02  17.790001
2015-01-05  19.920000
2015-01-06  21.120001
2015-01-07  19.309999
2015-01-08  17.010000